//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentHealthMonitor) DeepCopyInto(out *DeploymentHealthMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentHealthMonitor.
func (in *DeploymentHealthMonitor) DeepCopy() *DeploymentHealthMonitor {
	if in == nil {
		return nil
	}
	out := new(DeploymentHealthMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentHealthMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentHealthMonitorList) DeepCopyInto(out *DeploymentHealthMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DeploymentHealthMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentHealthMonitorList.
func (in *DeploymentHealthMonitorList) DeepCopy() *DeploymentHealthMonitorList {
	if in == nil {
		return nil
	}
	out := new(DeploymentHealthMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeploymentHealthMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthMonitorResourceResult) DeepCopyInto(out *HealthMonitorResourceResult) {
	*out = *in
	in.LastUpgradeStartTime.DeepCopyInto(&out.LastUpgradeStartTime)
	in.LastUpgradeEndTime.DeepCopyInto(&out.LastUpgradeEndTime)
	in.LastObservedUnhealthyTime.DeepCopyInto(&out.LastObservedUnhealthyTime)
	out.LastObservedUnhealthyDuration = in.LastObservedUnhealthyDuration
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthMonitorResourceResult.
func (in *HealthMonitorResourceResult) DeepCopy() *HealthMonitorResourceResult {
	if in == nil {
		return nil
	}
	out := new(HealthMonitorResourceResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthMonitorSpec) DeepCopyInto(out *HealthMonitorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthMonitorSpec.
func (in *HealthMonitorSpec) DeepCopy() *HealthMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(HealthMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthMonitorStatus) DeepCopyInto(out *HealthMonitorStatus) {
	*out = *in
	if in.Results != nil {
		in, out := &in.Results, &out.Results
		*out = make([]HealthMonitorStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthMonitorStatus.
func (in *HealthMonitorStatus) DeepCopy() *HealthMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(HealthMonitorStatus)
	in.DeepCopyInto(out)
	return out
}
